name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: CFLAGS=-DUSE_MINGW LDFLAGS=-lasprintf mingw32-make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
